#ifndef SIMDJSON2_IMPLEMENTATION_DETECTION_H
#define SIMDJSON2_IMPLEMENTATION_DETECTION_H

#include "simdjson2/base.h"

// 0 is reserved, because undefined SIMDJSON2_IMPLEMENTATION equals 0 in preprocessor macros.
#define SIMDJSON2_IMPLEMENTATION_ID_arm64 1
#define SIMDJSON2_IMPLEMENTATION_ID_fallback 2
#define SIMDJSON2_IMPLEMENTATION_ID_haswell 3
#define SIMDJSON2_IMPLEMENTATION_ID_icelake 4
#define SIMDJSON2_IMPLEMENTATION_ID_ppc64 5
#define SIMDJSON2_IMPLEMENTATION_ID_westmere 6
#define SIMDJSON2_IMPLEMENTATION_ID_lsx 7
#define SIMDJSON2_IMPLEMENTATION_ID_lasx 8

#define SIMDJSON2_IMPLEMENTATION_ID_FOR(IMPL) SIMDJSON2_CAT(SIMDJSON2_IMPLEMENTATION_ID_, IMPL)
#define SIMDJSON2_IMPLEMENTATION_ID SIMDJSON2_IMPLEMENTATION_ID_FOR(SIMDJSON2_IMPLEMENTATION)

#define SIMDJSON2_IMPLEMENTATION_IS(IMPL) SIMDJSON2_IMPLEMENTATION_ID == SIMDJSON2_IMPLEMENTATION_ID_FOR(IMPL)

//
// First, figure out which implementations can be run. Doing it here makes it so we don't have to worry about the order
// in which we include them.
//

#ifndef SIMDJSON2_IMPLEMENTATION_ARM64
#define SIMDJSON2_IMPLEMENTATION_ARM64 (SIMDJSON2_IS_ARM64)
#endif
#if SIMDJSON2_IMPLEMENTATION_ARM64 && SIMDJSON2_IS_ARM64
#define SIMDJSON2_CAN_ALWAYS_RUN_ARM64 1
#else
#define SIMDJSON2_CAN_ALWAYS_RUN_ARM64 0
#endif

// Default Icelake to on if this is x86-64. Even if we're not compiled for it, it could be selected
// at runtime.
#ifndef SIMDJSON2_IMPLEMENTATION_ICELAKE
#define SIMDJSON2_IMPLEMENTATION_ICELAKE ((SIMDJSON2_IS_X86_64) && (SIMDJSON2_AVX512_ALLOWED) && (SIMDJSON2_COMPILER_SUPPORTS_VBMI2))
#endif

#ifdef _MSC_VER
// To see why  (__BMI__) && (__PCLMUL__) && (__LZCNT__) are not part of this next line, see
// https://github.com/simdjson2/simdjson2/issues/1247
#if ((SIMDJSON2_IMPLEMENTATION_ICELAKE) && (__AVX2__) && (__AVX512F__) && (__AVX512DQ__) && (__AVX512CD__) && (__AVX512BW__) && (__AVX512VL__) && (__AVX512VBMI2__))
#define SIMDJSON2_CAN_ALWAYS_RUN_ICELAKE 1
#else
#define SIMDJSON2_CAN_ALWAYS_RUN_ICELAKE 0
#endif

#else

#if ((SIMDJSON2_IMPLEMENTATION_ICELAKE) && (__AVX2__) && (__BMI__) && (__PCLMUL__) && (__LZCNT__) && (__AVX512F__) && (__AVX512DQ__) && (__AVX512CD__) && (__AVX512BW__) && (__AVX512VL__) && (__AVX512VBMI2__))
#define SIMDJSON2_CAN_ALWAYS_RUN_ICELAKE 1
#else
#define SIMDJSON2_CAN_ALWAYS_RUN_ICELAKE 0
#endif

#endif

// Default Haswell to on if this is x86-64. Even if we're not compiled for it, it could be selected
// at runtime.
#ifndef SIMDJSON2_IMPLEMENTATION_HASWELL
#if SIMDJSON2_CAN_ALWAYS_RUN_ICELAKE
// if icelake is always available, never enable haswell.
#define SIMDJSON2_IMPLEMENTATION_HASWELL 0
#else
#define SIMDJSON2_IMPLEMENTATION_HASWELL SIMDJSON2_IS_X86_64
#endif
#endif
#ifdef _MSC_VER
// To see why  (__BMI__) && (__PCLMUL__) && (__LZCNT__) are not part of this next line, see
// https://github.com/simdjson2/simdjson2/issues/1247
#if ((SIMDJSON2_IMPLEMENTATION_HASWELL) && (SIMDJSON2_IS_X86_64) && (__AVX2__))
#define SIMDJSON2_CAN_ALWAYS_RUN_HASWELL 1
#else
#define SIMDJSON2_CAN_ALWAYS_RUN_HASWELL 0
#endif

#else

#if ((SIMDJSON2_IMPLEMENTATION_HASWELL) && (SIMDJSON2_IS_X86_64) && (__AVX2__) && (__BMI__) && (__PCLMUL__) && (__LZCNT__))
#define SIMDJSON2_CAN_ALWAYS_RUN_HASWELL 1
#else
#define SIMDJSON2_CAN_ALWAYS_RUN_HASWELL 0
#endif

#endif

// Default Westmere to on if this is x86-64.
#ifndef SIMDJSON2_IMPLEMENTATION_WESTMERE
#if SIMDJSON2_CAN_ALWAYS_RUN_ICELAKE || SIMDJSON2_CAN_ALWAYS_RUN_HASWELL
// if icelake or haswell are always available, never enable westmere.
#define SIMDJSON2_IMPLEMENTATION_WESTMERE 0
#else
#define SIMDJSON2_IMPLEMENTATION_WESTMERE SIMDJSON2_IS_X86_64
#endif
#endif

#if (SIMDJSON2_IMPLEMENTATION_WESTMERE && SIMDJSON2_IS_X86_64 && __SSE4_2__ && __PCLMUL__)
#define SIMDJSON2_CAN_ALWAYS_RUN_WESTMERE 1
#else
#define SIMDJSON2_CAN_ALWAYS_RUN_WESTMERE 0
#endif


#ifndef SIMDJSON2_IMPLEMENTATION_PPC64
#define SIMDJSON2_IMPLEMENTATION_PPC64 (SIMDJSON2_IS_PPC64 && SIMDJSON2_IS_PPC64_VMX)
#endif
#if SIMDJSON2_IMPLEMENTATION_PPC64 && SIMDJSON2_IS_PPC64 && SIMDJSON2_IS_PPC64_VMX
#define SIMDJSON2_CAN_ALWAYS_RUN_PPC64 1
#else
#define SIMDJSON2_CAN_ALWAYS_RUN_PPC64 0
#endif

#ifndef SIMDJSON2_IMPLEMENTATION_LASX
#define SIMDJSON2_IMPLEMENTATION_LASX (SIMDJSON2_IS_LOONGARCH64 && __loongarch_asx)
#endif
#define SIMDJSON2_CAN_ALWAYS_RUN_LASX (SIMDJSON2_IMPLEMENTATION_LASX)

#ifndef SIMDJSON2_IMPLEMENTATION_LSX
#if SIMDJSON2_CAN_ALWAYS_RUN_LASX
#define SIMDJSON2_IMPLEMENTATION_LSX 0
#else
#define SIMDJSON2_IMPLEMENTATION_LSX (SIMDJSON2_IS_LOONGARCH64 && __loongarch_sx)
#endif
#endif
#define SIMDJSON2_CAN_ALWAYS_RUN_LSX (SIMDJSON2_IMPLEMENTATION_LSX)

// Default Fallback to on unless a builtin implementation has already been selected.
#ifndef SIMDJSON2_IMPLEMENTATION_FALLBACK
#if SIMDJSON2_CAN_ALWAYS_RUN_ARM64 || SIMDJSON2_CAN_ALWAYS_RUN_ICELAKE || SIMDJSON2_CAN_ALWAYS_RUN_HASWELL || SIMDJSON2_CAN_ALWAYS_RUN_WESTMERE || SIMDJSON2_CAN_ALWAYS_RUN_PPC64 || SIMDJSON2_CAN_ALWAYS_RUN_LSX || SIMDJSON2_CAN_ALWAYS_RUN_LASX
// if anything at all except fallback can always run, then disable fallback.
#define SIMDJSON2_IMPLEMENTATION_FALLBACK 0
#else
#define SIMDJSON2_IMPLEMENTATION_FALLBACK 1
#endif
#endif
#define SIMDJSON2_CAN_ALWAYS_RUN_FALLBACK SIMDJSON2_IMPLEMENTATION_FALLBACK

// Determine the best builtin implementation
#ifndef SIMDJSON2_BUILTIN_IMPLEMENTATION

#if SIMDJSON2_CAN_ALWAYS_RUN_ICELAKE
// #define SIMDJSON2_BUILTIN_IMPLEMENTATION icelake
#elif SIMDJSON2_CAN_ALWAYS_RUN_HASWELL
#define SIMDJSON2_BUILTIN_IMPLEMENTATION haswell
#elif SIMDJSON2_CAN_ALWAYS_RUN_WESTMERE
//#define SIMDJSON2_BUILTIN_IMPLEMENTATION westmere
#elif SIMDJSON2_CAN_ALWAYS_RUN_ARM64
#define SIMDJSON2_BUILTIN_IMPLEMENTATION arm64
#elif SIMDJSON2_CAN_ALWAYS_RUN_PPC64
#define SIMDJSON2_BUILTIN_IMPLEMENTATION ppc64
#elif SIMDJSON2_CAN_ALWAYS_RUN_LSX
#define SIMDJSON2_BUILTIN_IMPLEMENTATION lsx
#elif SIMDJSON2_CAN_ALWAYS_RUN_LASX
#define SIMDJSON2_BUILTIN_IMPLEMENTATION lasx
#elif SIMDJSON2_CAN_ALWAYS_RUN_FALLBACK
#define SIMDJSON2_BUILTIN_IMPLEMENTATION fallback
#else
#error "All possible implementations (including fallback) have been disabled! simdjson2 will not run."
#endif

#endif // SIMDJSON2_BUILTIN_IMPLEMENTATION

#define SIMDJSON2_BUILTIN_IMPLEMENTATION_ID SIMDJSON2_IMPLEMENTATION_ID_FOR(SIMDJSON2_BUILTIN_IMPLEMENTATION)
#define SIMDJSON2_BUILTIN_IMPLEMENTATION_IS(IMPL) SIMDJSON2_BUILTIN_IMPLEMENTATION_ID == SIMDJSON2_IMPLEMENTATION_ID_FOR(IMPL)

#endif // SIMDJSON2_IMPLEMENTATION_DETECTION_H
