// /include/simdjson2/simdjson2_version.h automatically generated by release.py,
// do not change by hand
#ifndef SIMDJSON2_SIMDJSON2_VERSION_H
#define SIMDJSON2_SIMDJSON2_VERSION_H

/** The version of simdjson2 being used (major.minor.revision) */
#define SIMDJSON2_VERSION "3.10.1"

namespace simdjson2 {
enum {
  /**
   * The major version (MAJOR.minor.revision) of simdjson2 being used.
   */
  SIMDJSON2_VERSION_MAJOR = 3,
  /**
   * The minor version (major.MINOR.revision) of simdjson2 being used.
   */
  SIMDJSON2_VERSION_MINOR = 10,
  /**
   * The revision (major.minor.REVISION) of simdjson2 being used.
   */
  SIMDJSON2_VERSION_REVISION = 1
};
} // namespace simdjson2

#endif // SIMDJSON2_SIMDJSON2_VERSION_H
