#ifndef SIMDJSON2_CONDITIONAL_INCLUDE
#include "simdjson2/haswell/base.h"
#endif // SIMDJSON2_CONDITIONAL_INCLUDE

#if !SIMDJSON2_CAN_ALWAYS_RUN_HASWELL
SIMDJSON2_UNTARGET_REGION
#endif

#undef SIMDJSON2_IMPLEMENTATION
