#ifdef SIMDJSON2_CONDITIONAL_INCLUDE
#error generic/dependencies.h must be included before defining SIMDJSON2_CONDITIONAL_INCLUDE!
#endif

#ifndef SIMDJSON2_SRC_GENERIC_DEPENDENCIES_H
#define SIMDJSON2_SRC_GENERIC_DEPENDENCIES_H

#include <base.h>

#endif // SIMDJSON2_SRC_GENERIC_DEPENDENCIES_H
